name: HotbarPets
version: ${project.version}
author: TheBusyBiscuit
depend: [Slimefun]
softdepend: [ANOSF, BreweryX, InfinityExpansion2]
api-version: 1.21

main: io.github.thebusybiscuit.hotbarpets.HotbarPets
